afafmmm/6-FavoritePhoto-4team-be

-  auth.http
- package-lock.json
- package.json
- prisma/schema.prisma
- src/app.js
- src/config/passport.js
- src/controllers/AuthController.js
- src/middlewares/passport/JwtStrategy.js
- src/repositories/AuthRepository.js
- src/services/AuthService.js
- src/utils/async-handler.js
---
---
- 작업 1 auth API 로컬부분 구현
- 작업 2
- 작업 3
---
-
-
> feat: auth API 로컬부분 구현

-  auth.http
- src/controllers/AuthController.js
---
---
- 작업 1 auth API 쿠키 설정 수정
- 작업 2
- 작업 3
---
-
-
> feat: auth API 쿠키 설정 수정

- src/services/AuthService.js
- [x ] `fix:` 버그를 수정한 커밋
---
---
- 작업 1 fix: Auth레파지토리 수정
- 작업 2
- 작업 3
---
-
-
> fix: Auth레파지토리 수정

- src/app.js
---
---
- 작업 1 cors 주소 재수정
- 작업 2
- 작업 3
---
-
-
> cors 주소 재수정

- src/app.js
- src/controllers/StoreController.js
---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-
> 백엔드셋팅변경 및 store 인증추가

- src/controllers/UsersController.js
- src/repositories/UsersRepository.js
---
제곧내
---
- 지금까지는 카드 생성 실패하면 이미지가 깨진 채로 저장됐는데 저장 안 되게 함
---
> Feat: 카드 생성 실패하면 이미지 삭제되게 함

- src/app.js
- src/controllers/NotificationsController.js
- src/repositories/NotificationsRepository.js
- src/services/NotificationsService.js
---
알림 API 구현 
---
- 알림 생성
- 알림 전체 조회 (user ID)
- 알림 단건 조회(알림 id)
- 알림 읽음 처리(알림 id)
- 알림 삭제 (알림 id)
---
-
-
> feat:알림 생성,전체 조회,단건 조회,읽음처리,알림 삭제

- src/repositories/UsersRepository.js
---
마이 갤러리 조회 repository에 user nickname 가져오는 거 없어서 수정
---
제곧내
---
> Fix: 조회 api 수정

- src/app.js
- src/controllers/StoreController.js
- src/controllers/TradeRequestController.js
- src/repositories/StoreRepository.js
- src/repositories/TradeRequestRepository.js
- src/services/StoreService.js
- src/services/TradeRequestService.js
- test.http
---
---교환 추가, 취소 추가
- 교환 추가, 취소 추가- 작업 2
- 작업 3
---
-
-
> Feature/store2 교환 추가, 취소 추가

- src/repositories/UsersRepository.js
- src/services/AuthService.js
- src/services/UsersService.js
- src/utils/pagination.js
- test.http
---
---
- 작업 1 백엔드 pagination 구현 및 테스트
- 작업 2
- 작업 3
---
-
-
> feat:백엔드 pagination 구현 및 테스트

- src/controllers/StoreController.js
- src/repositories/StoreRepository.js
- src/services/StoreService.js
---
Feat: 마켓 플레이스 정렬 기능 넣음
---
Feat: 마켓 플레이스 정렬 기능 넣음
---
Feat: 마켓 플레이스 정렬 기능 넣음
> Feat: 마켓 플레이스 정렬 기능 넣음

- prisma/migrations/20250528080640_add/migration.sql
- prisma/migrations/20250528080928_add_on_delete_point_default/migration.sql
- prisma/schema.prisma
---
유저 삭제시 관련 데이터 삭제가능하게 스키마 수정
포인트 기본 지급 10
---
- 작업 1
- 작업 2
- 작업 3
---
-
-
> fix:스키마 온딜리트,포인트 기본값 추가

- src/repositories/UsersRepository.js
---
판매/구매에서 같이 쓸 수 있게 api 수정
---
판매/구매에서 같이 쓸 수 있게 api 수정
---
판매/구매에서 같이 쓸 수 있게 api 수정
> chore: take1 지움

- src/controllers/SalesController.js
- src/controllers/TradeController.js
- src/repositories/SalesRepository.js
- src/repositories/TradeRepository.js
- src/services/SalesService.js
- src/services/TradeService.js
---
--- 전체적 수정 
- 작업 1
- 작업 2
- 작업 3
---
-
-
> [김다은] udpate: Sale, Trade

- src/repositories/UsersRepository.js
- src/services/UsersService.js
- src/utils/pagination.js
---
쿼리 문자열 구현 완료
---
쿼리 문자열 구현 완료
---
쿼리 문자열 구현 완료
> fix: 마이 갤러리 진짜 최종

- src/repositories/UsersRepository.js
- src/services/UsersService.js
---
feat: 판매 페이지 api 수정
---
feat: 판매 페이지 api 수정
---
-
-
> feat: 판매 페이지 api 수정

- src/repositories/UsersRepository.js
---
필터 두 개 빼고 판매 페이지 진짜 끝
---
필터 두 개 빼고 판매 페이지 진짜 끝
---
필터 두 개 빼고 판매 페이지 진짜 끝
> 필터 두 개 빼고 판매 페이지 진짜 끝

- src/repositories/UsersRepository.js
---
fix: 판매 페이지 available 빼고 안 떠서 확인 중
---
fix: 판매 페이지 available 빼고 안 떠서 확인 중
---
-
-
> fix: 판매 페이지 available 빼고 안 떠서 확인 중

- src/services/Purchaseservice.js
- test.http
---
message 코드 누락 수정
---
- message 코드 누락 수정
- 작업 2
- 작업 3
---
-
-
> fix: 구매/판매 알림 수정

- src/controllers/StoreController.js
- src/controllers/UsersController.js
- src/repositories/StoreRepository.js
- src/repositories/TradeRequestRepository.js
- src/repositories/UsersRepository.js
- src/services/StoreService.js
- src/services/TradeRequestService.js
- src/services/UsersService.js
- src/utils/filter.js
- test.http
---
--- 메인페이지 카운트 추가 중
- 작업 1
- 작업 2
- 작업 3
---
-
-
> Feature/store2 메인페이지 카운트 추가 중

- src/repositories/StoreRepository.js
- src/services/StoreService.js
---
---메인페이지 바텀시트 추가
- 작업 1
- 작업 2
- 작업 3
---
-
-
> feat: 메인페이지 바텀시트 추가

- src/controllers/UsersController.js
- src/repositories/UsersRepository.js
- src/services/UsersService.js
---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-
> feat: 성경님 마이갤러리 코드에 카운트 추가

- src/repositories/SalesRepository.js
- src/repositories/TradeRepository.js
---
--- 교환 승인 다시 정상 작동
- 작업 1
- 작업 2
- 작업 3
---
-
-
> [김다은] update: 교환 승인 기능 수정

- src/repositories/UsersRepository.js
---
style: 필터 매개변수 이름을 변경했음
---
style: 필터 매개변수 이름을 변경했음
---
style: 필터 매개변수 이름을 변경했음
> style: 필터 매개변수 이름을 변경했음

- src/controllers/UsersController.js
- src/repositories/UsersRepository.js
- src/services/UsersService.js
--- 판매중인 마이페이지 바텀시트 추가
---
- 작업 1
- 작업 2
- 작업 3
---
-
-
> Feature/store2 판매중인 마이페이지 바텀시트 추가

- src/controllers/Purchasecontroller.js
---
io 객체 누락 수정
---
- Purchasecontroller 에서 io 객체 가져오도록 수정
---
-
-
> fix: Purchasecontoroller.js io 추가

- src/services/TradeRequestService.js
---
fix:tx 오류 해결,카드 등급 불러오기 로직 수정
---
fix:tx 오류 해결,카드 등급 불러오기 로직 수정
- 작업 1
- 작업 2
- 작업 3
---
-
-
> fix:tx 오류 해결,카드 등급 불러오기 로직 수정

- src/services/TradeRequestService.js
---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-
> fix:알림 오류 수정

- src/services/TradeRequestService.js
---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-
> fix:알림 누락 수정

- src/services/Purchaseservice.js
- src/services/TradeRequestService.js
---
카드 품절 알림 추가
---
- 카드 품절 알림 코드 추가
- 교환 제안 웹소캣 객체 코드 누락 수정
---
-
-
> feat:카드 품절 알림

- src/controllers/TradeController.js
- src/repositories/TradeRepository.js
- src/services/TradeService.js
---
교환 성사/불발 알림 
---
- 교환 불발 알림 TradeService 에 추가
- 교환 성사 알림 TradeRepo 에 추가
---
-
-
> feat:교환 성사,불발 알림

- src/repositories/TradeRepository.js
---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-
> fix:TradeRepository.js의 NOtificationService.js 임포트 경로 수정

- src/repositories/TradeRepository.js
- src/services/TradeService.js
---
- 교환 성사 알림 웹 소켓 객체 전달 누락 수정
- 교환 성사,불발시 나오는 카드의 장르가 나오던 문제 수정
---
- 교환 성사 알림 웹 소켓 객체 전달 누락 수정
- 교환 성사,불발시 나오는 카드의 장르가 나오던 문제 수정
---
-
-
> fix:교환 승인 io객체 전달 누락 수정

- src/controllers/StoreController.js
- src/repositories/StoreRepository.js
- src/services/StoreService.js
---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-
> 무한 스크롤 기능 구현

- src/utils/filter.js
---
우주 님 필터 수정
---
우주 님 필터 수정
---
우주 님 필터 수정
> fix: 필터 수정

- src/repositories/UsersRepository.js
---
교환 불러오는 데이터 수정
---
교환 불러오는 데이터 수정
---
교환 불러오는 데이터 수정
> fix: 교환 불러오는 데이터 수정

- src/repositories/UsersRepository.js
---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-
> fix: 나의 판매 페이지 필터 조금 수정

- src/repositories/UsersRepository.js
---
console.log 지움
---
console.log 지움
---
console.log 지움
> refactor: console.log 지움

- src/repositories/TradeRepository.js
---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-
> [김다은] update: 거래 승인쪽 버그 수정
